### ISSUE TITLE
Custom defines as compile argument

### ISSUE THREAD

**Issue by Pimmetje** [robgonnella/ardi#14]
As suggested in #9. It would be nice if we can specify -D arguments so it can use custom defines when we run compile. For example to make a debug build.

**Comment by robgonnella** [comment]
Just added the ability to specify custom build properties to the compiler.

https://github.com/robgonnella/ardi#build-properties

**Comment by robgonnella** [comment]
Also the compile command now gives you the option to print all build properties without compiling so you can see if your custom arguments are being set properly. Just add `--show-props` to your compile command.

**Comment by Pimmetje** [comment]
Ill test it tomorrow i think. Thanks
