### ISSUE TITLE
build command to run predefined compile commands

### ISSUE THREAD

**Issue by Pimmetje** [robgonnella/ardi#15]
In the ardi.json it would be nice if we can define multiple compile commands. Every compile command should get a name. The resulting hex file should include this name so it will not be overwritten by other compile commands. 

running `ardi build` should execute all compile commands in order. As a bonus there could be extra options to run only a subset.

**Comment by robgonnella** [comment]
Hey so I know it's been a while but this feature has been implemented now in v2. To try it out run
```
GO111MODULE=on go get github.com/robgonnella/ardi/v2
```
