### ISSUE TITLE
Compile HEX without a board

### ISSUE THREAD

**Issue by Pimmetje** [robgonnella/ardi#6]
Currently it seems that the arduino board if taken from the attached arduino board. As this is useful for beginners i think it should be possible to define it yourself. 

Also it would be useful to only compile to a hex file. Without upload or any attached board.

**Comment by robgonnella** [comment]
This feature has now been added: See https://github.com/robgonnella/ardi/pull/4

**Comment by Pimmetje** [comment]
Works for me, thx
