### ISSUE TITLE
CONSIDER a command like "ardi compile-and-upload"?

### ISSUE THREAD

**Issue by egnor** [robgonnella/ardi#87]
I continue to use and love Ardi!! 🙏 I am recommending it to everyone!

A very very common use case is to run `ardi compile` followed by `ardi upload`. If one is not careful, it's easy to forget the `compile` step, or not notice a failure, and upload an old firmware image from a previous compilation.

Possibilities:
- Add an `ardi compile-and-upload` command (that takes the union of both steps options), which can become the standard thing to run for programming (similar to `attach-and-watch`).
- Make `ardi upload` complain (perhaps even fail) if the firmware image is older than the source `.ino` file (and its dependencies??).
- Or maybe even make `ardi upload` always build as needed??

**Comment by robgonnella** [comment]
Thanks for the continued support!! ❤️ 

I like the idea of adding a `compile-and-upload` command while keeping the `upload` command pure. This way the intent is always clear. I've already started on a draft of this approach.

I'll look into making the upload command complain if the firmware image is older than the source `.ino` but I'll refrain from failing so as not to make assumptions about what the user intends.

Once again thank you for the awesome suggestions!

**Comment by robgonnella** [comment]
Done and released in `v2.4.0` !
I've also added the command aliases to the docs and the help menus. For example `ardi compile-and-upload` can also be called via `ardi deploy`
