### ISSUE TITLE
Can't upload to Adafruit Feather nRF52832 board

### ISSUE THREAD

**Issue by egnor** [robgonnella/ardi#94]
While ardi can in fact program the Adafruit Circuit Playground "Bluefruit" nRF52840 and thus probably the very similar Feather nRF52840, attempting to upload to the Feather nRF52832 fails with a message about not being able to detect any boards (precise output available on request). Note that the USB-Serial differs significantly between these models, Adafruit's design uses built-in USB on the nRF52840 board but use a CP2104 USB-Serial chip on the nRF52832 board.

This happens even with "-p /dev/ttyUSB0" to point it to the direct serial port (on my Linux host), which seems like it should override detection?

The regular Arduino IDE is able to program this board with no problem, using that serial port.

(Happy to send you some of these boards, or run with more diagnostics or whatnot.)

**Comment by robgonnella** [comment]
Apologies for the delay on this it's been a hectic 6 months. Did you try using both `-p` and `-f`. My guess is that for some reason the board discovery module (provided by aruduino-cli), cannot find the board. If you provide both the port and the fqbn it should have all it needs to be able to successfully upload.
